### ISSUE TITLE
Doesn't Register a 2nd GA event for same element

### ISSUE THREAD

**Issue by pickerflicker** [panrafal/angular-ga#4]
Hi, I'm using the GA directing in html.  I've noticed that when I click on the same button multiple times, it only fires a GA event every other click.  ie: if i click a button 5 times, it'll only send events for the 1st,3rd,5th click.

Has anyone else encountered this?

**Comment by raghu64** [comment]
@panrafal I'm using bower to install angular-ga, but i don't see the fix for this issue in 0.1.3
