### ISSUE TITLE
How to set userId dynamically?

### ISSUE THREAD

**Issue by perqa** [panrafal/angular-ga#5]
I want to implement cross-device logging which requires userId. This has to be set dynamically after login, like this:  ga('create', 'UA-XXXX-Y', { 'userId': 'USER_ID' });

Can I do this with angular-ga?  

Ref: https://developers.google.com/analytics/devguides/collection/analyticsjs/user-id

**Comment by panrafal** [comment]
Sure! Just call it as stated in the analytics docs on Your login handler and add `ga` as a dependency injection. Like here: https://github.com/panrafal/angular-ga/blob/master/README.md#use-ga-service-in-your-controllers-directives-etc
